name: Schedule Workflow

on:
  schedule:
    - cron: "15 18 * * *"
  workflow_dispatch:

jobs:
  Run-Script:
    runs-on: ubuntu-latest

    steps:
      - name: Print Message
        run: |
          echo "Welcome to Devops Course"
          echo "Current UTC time:"
          date -u
