name: Schedule Workflow

on:
  schedule:
    - cron: "49 17 * * *"

jobs:
  Run-Script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Message
        run: echo "Welcome to Devops Course"
